### ISSUE TITLE
2017 Project tasklist/wishlist

### ISSUE THREAD

**Issue by guruofquality** [pothosware/PothosCore#109]
With a myriad of things to do, here is an overall feature goal list for the year to prioritize some things. Feel free to extend/comment:

* [x] Rewrite gui evaluator - https://github.com/pothosware/pothos-gui/issues/97
* [ ] Graphical Filter design blocks based on [spuce]( https://github.com/audiofilter/spuce/blob/master/README.md)
  * [ ] installable widget library additions for spuce
* [x] toolkit for [liquid dsp](https://github.com/pothosware/pothos/issues/17) processing blocks
* [ ] Support GUI creation of hierarchies: https://github.com/pothosware/pothos-gui/issues/127
* [ ] Export of GUI design to Qt application
* [x] Block overlays - https://github.com/pothosware/pothos-gui/issues/75
* [ ] General topology API improvements
  * https://github.com/pothosware/pothos/issues/97
  * https://github.com/pothosware/pothos/issues/64
  * https://github.com/pothosware/pothos/issues/73

**Comment by guruofquality** [comment]
Glad we could knock some of these off. Happy new year!
