### ISSUE TITLE
Checklist for updating after port API additions

### ISSUE THREAD

**Issue by guruofquality** [pothosware/PothosCore#145]
* [x] matching changelog entry about api
* [x] merge feature branch block_resource_moves
* [x] update blocks coding guide to use buffer cast operator `int *p = port->buffer()`
* [x] switch to buffer cast syntax in the various toolkits
* [x] use label emplacement w/ postLabel when applicable in blocks
* [x] use move for labels, packets, messages, buffers when applicable

**Comment by guruofquality** [comment]
additional documentation https://github.com/pothosware/PothosCore/wiki/Release06
