### ISSUE TITLE
Pothos 0.6 release checklist

### ISSUE THREAD

**Issue by guruofquality** [pothosware/PothosCore#146]
* [x] port api additions: https://github.com/pothosware/PothosCore/issues/145
* [x] actor interface internals: https://github.com/pothosware/PothosCore/pull/144
* [x] update to use new JSON library
* [x] Callable and Proxy API call variants
* [x] tag toolkits
* [x] tag pothos core
* [x] update homebrew
  * [x] and update for renames to PothosFlow, PothosCore, PothosSoapy
  * [x] and update wiki instructions
* [x] new PothosSDR build
  * [x] and update for renames to PothosFlow, PothosCore, PothosSoapy
  * [x] and update wiki instructions and screenshots
* [x] upload to PPA 16.04 + current release
* [x] release announcement
* [x] doxygen update

**Comment by guruofquality** [comment]
Release announcement: https://groups.google.com/forum/#!topic/pothos-users/mnhrTo87Vvw
